name: lab10
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  badges: ^3.1.2
  consumer: ^2.3.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_cart: ^0.0.9
  flutter_lints: ^3.0.2
  fluttertoast: ^8.2.5
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
